services:
  - type: web
    name: 30-day-health-tracker
    runtime: node
    buildCommand: npm install --loglevel verbose

    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
